set_property PACKAGE_PIN W10 [get_ports {BTN[1]}]
set_property PACKAGE_PIN W11 [get_ports {BTN[0]}]
set_property PACKAGE_PIN W8 [get_ports {LED[1]}]
set_property PACKAGE_PIN W9 [get_ports {LED[0]}]
set_property PACKAGE_PIN AA19 [get_ports CLK]

set_property IOSTANDARD LVCMOS18 [get_ports {BTN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BTN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports CLK]
