set_property IOSTANDARD LVCMOS18 [get_ports {BTN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BTN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports CLK_P]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports CLK_N]
set_property IOSTANDARD LVCMOS18 [get_ports UART_TXD]
set_property IOSTANDARD LVCMOS18 [get_ports UART_RXD]

set_property PACKAGE_PIN W10 [get_ports {BTN[1]}]
set_property PACKAGE_PIN W11 [get_ports {BTN[0]}]
set_property PACKAGE_PIN V12 [get_ports {LED[1]}]
set_property PACKAGE_PIN W8 [get_ports {LED[0]}]
set_property PACKAGE_PIN AB19 [get_ports CLK_P]
set_property PACKAGE_PIN AB20 [get_ports CLK_N]
set_property PACKAGE_PIN W9 [get_ports UART_RXD]
set_property PACKAGE_PIN V11 [get_ports UART_TXD]
